### PR TITLE
Fix `tidySymbol` to not drop arg-id

### LINKED ISSUE #658: Missing suffix in var when printing solution with --save
The following constraint

```
(qualif EqZero ((a0 int)) (a0 = 0))
(qualif GtZero ((a0 int)) (a0 > 0))
(qualif GeZero ((a0 int)) (a0 >= 0))
(qualif LtZero ((a0 int)) (a0 < 0))
(qualif LeZero ((a0 int)) (a0 <= 0))
(qualif Eq ((a0 int) (a1 int)) (a0 = a1))
(qualif Gt ((a0 int) (a1 int)) (a0 > a1))
(qualif Ge ((a0 int) (a1 int)) (a0 >= a1))
(qualif Lt ((a0 int) (a1 int)) (a0 < a1))
(qualif Le ((a0 int) (a1 int)) (a0 <= a1))
(qualif Le1 ((a0 int) (a1 int)) (a0 <= (a1 - 1)))
(data Pair 2 = [| Pair { fst: @(0), snd: @(1) } ])
(data Unit 0 = [| Unit { }])
(var $k0 ((int) (int)))

(constraint
  (forall ((a0 int) (true))
    (forall ((_ Unit) (a0 >= 0))
      (and
        (forall ((a1 int) (a1 = 0))
          (tag ($k0 a1 a0) "0")
        )
        (forall ((a2 int) (true))
          (forall ((_ Unit) ($k0 a2 a0))
            (and
              (forall ((_ Unit) (~(a2 < a0)))
                (tag (a2 = a0) "1")
              )
              (forall ((_ Unit) (a2 < a0))
                (forall ((a3 int) (a3 = (a2 + 1)))
                  (tag ($k0 a3 a0) "2")
                )
              )
            )
          )
        )
      )
    )
  )
)
```
produces the following output when I run `fixpoint --save` on it

```
Solution:
$k0 := nnf_arg##k0 >= 0
       && nnf_arg##k0 <= nnf_arg##k0


Non-cut kvars:
```

Seems like the pretty printing is missing the suffix indicating the variable.

### PR DESCRIPTION
**Pull request by ranjitjhala**
- also separate `unKArgSymbol` for matching qual-patterns

fixes #658

### CODE REVIEW

File: src/Language/Fixpoint/Types/Names.hs [hunk 1]
```diff
@@ -518,7 +518,7 @@ tidySymbol s
   | otherwise = s''
   where
     s'        = unPrefixSymbol kArgPrefix s
-    s''       = unPrefixSymbol symSepName . unPrefixSymbol hvarPrefix $ s'
+    s''       = consSym '$' . unPrefixSymbol symSepName . unSuffixSymbol . unPrefixSymbol hvarPrefix $ s'
```
Comment (facundominguez) [inline src/Language/Fixpoint/Types/Names.hs:539]: I'm out of my depth here, but I just wanted to suggest adding a comment to `tidySymbol` explaining what it is meant to do.

**Review by facundominguez — APPROVED** [review]

File: src/Language/Fixpoint/Types/Names.hs (hunk 1 above)
Comment (facundominguez) [reply src/Language/Fixpoint/Types/Names.hs:539]: And similar suggestion for the other functions modified in the PR. Alternatively, perhaps the source code could be made more self explanatory if the structure of the symbols is explained in a comment.

**Comment by ranjitjhala** [comment]
Excellent suggestion @facundo, will do!
