### PR TITLE
Use dot instead of hyphen as separator for model.partial.

### LINKED ISSUE #614: `z3-4.10.*` versions don't work for liquid-fixpoint
After `brew upgrade z3` I found that `cabal test all` for `liquid-fixpoint` had failures.

Incidentally I found that `pavpanchekha/setup-z3@1.2.2` can't install the latest version of z3 as ubuntu binaries are no longer being built or maybe they are under another name (a separate issue).

```yaml
      - name: Setup z3
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: "4.8.7"
```

This `pavpanchekha/setup-z3` file name construction doesn't work for some of the newer releases.

```js
    let path = "https://github.com/Z3Prover/z3/releases/download/z3-" + version;
    let file = "z3-" + version + "-" + architecture + "-" + distribution + ".zip";
```

Screen Shot 2022-08-02 at 7 16 50 AM

I uninstalled with `brew uninstall z3`, downloaded binaries for osx to `$HOME/dev/tools/z3/` and used [direnv](https://direnv.net/) in the `liquid-fixpoint` project root to switch z3 versions that I tested with `cabal test all`.

```
# .envrc file contents

# These z3 versions work for liquid-fixpoint's test-suite.
# PATH_add "$HOME/dev/tools/z3/z3-4.8.7-x64-osx-10.14.6/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.8.10-x64-osx-10.15.7/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.8.17-x64-osx-10.16/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.9.0-x64-osx-10.16/bin"

# The z3-4.10.* versions don't work for liquid-fixpoint.
PATH_add "$HOME/dev/tools/z3/z3-4.10.0-x64-osx-10.16/bin"
# PATH_add "$HOME/dev/tools/z3/z3-4.10.2-x64-osx-10.16/bin"
```

### PR DESCRIPTION
**Pull request by philderbeast**
This fixes #614 when `z3 >= 4.10`.

~~Please don't merge until our gh-actions are able to install z3 at that version. We currently install `z3-4.8.7`.~~

Update: I tested with `z3-4.8.7` and it is all good.

```
> cabal run fixpoint --  tests/horn/pos/test01.smt2
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - liquid-fixpoint-0.8.10.7.1 (lib) (configuration changed)
 - liquid-fixpoint-0.8.10.7.1 (exe:fixpoint) (configuration changed)
Configuring library for liquid-fixpoint-0.8.10.7.1..
Preprocessing library for liquid-fixpoint-0.8.10.7.1..
Building library for liquid-fixpoint-0.8.10.7.1..
Configuring executable 'fixpoint' for liquid-fixpoint-0.8.10.7.1..
Preprocessing executable 'fixpoint' for liquid-fixpoint-0.8.10.7.1..
Building executable 'fixpoint' for liquid-fixpoint-0.8.10.7.1..


Liquid-Fixpoint Copyright 2013-21 Regents of the University of California.
All Rights Reserved.

Working 166% [==============================================================]
Safe ( 2  constraints checked)

> z3 --version
Z3 version 4.8.7 - 64 bit
```

### CODE REVIEW

**Comment by philderbeast** [comment]
https://github.com/ucsd-progsys/liquid-fixpoint/blob/d37f7330f7bf45410e37c504e17667b318942089/src/Language/Fixpoint/Smt/Interface.hs#L523-L534

@facundominguez now that the options are the same (above), can we remove this code (below)?

https://github.com/ucsd-progsys/liquid-fixpoint/blob/d37f7330f7bf45410e37c504e17667b318942089/src/Language/Fixpoint/Smt/Interface.hs#L356-L366

**Comment by facundominguez** [comment]
> @facundominguez now that the options are the same (above), can we remove this code (below)?

Looks so to me. It would be easy enough to revert. If LF should support older versions of `z3`, arguably, they should be tested in CI too.

**Comment by philderbeast** [comment]
I tested with `z3-4.8.7` and `z3-4.10.2` locally and it passed after removing "DON'T REMOVE THIS".

File: src/Language/Fixpoint/Smt/Interface.hs [hunk 1]
```diff
@@ -353,15 +353,12 @@ smtCmd Z3      = "z3 -smt2 -in"
 smtCmd Mathsat = "mathsat -input=smt2"
 smtCmd Cvc4    = "cvc4 --incremental -L smtlib2"
 
--- DON'T REMOVE THIS! z3 changed the names of options between 4.3.1 and 4.3.2...
```
Comment (philderbeast) [inline src/Language/Fixpoint/Smt/Interface.hs:356]: Those versions are dated looking at the tags, 4.3.1 (2012) and 4.3.2 (2014).

**Review by facundominguez — APPROVED** [review]
Thanks @philderbeast!

**Comment by philderbeast** [comment]
@facundominguez thanks for prompting me to try `model.partial`.
