### PR TITLE
Write shrinker for undoANF tests; print problems on unify; fix undoANF Arbitrary instance

### LINKED ISSUE #557: SortChecl: lookup in Empty Env
Found on #555.

```
> cabal test all
...
  undoANFSimplifyingWith id id
    id on empty env:                           OK
    id when env contains no lq_anf$* bindings: OK (0.10s)
      +++ OK, passed 500 tests.
    zero anf vars left afterwards, starting with:
      no anf vars:                             OK (0.05s)
        +++ OK, passed 500 tests.
      single-level anf vars:                   FAIL
...
        Use --quickcheck-replay=407282 --quickcheck-max-size=8 to reproduce.
        Use -p '/single-level anf vars/' to rerun this test only.
```

How I went about checking if it is reproducible (after adding hidden dependencies to the tasty test-suite so that I could run in it the REPL):

```
> stack repl liquid-fixpoint:tasty
...
:main --quickcheck-replay=407282 --quickcheck-max-size=8 "--pattern=single-level anf vars"
Tests
  undoANFSimplifyingWith id id
    zero anf vars left afterwards, starting with:
      single-level anf vars: FAIL (0.01s)
        *** Failed! Exception: 'Error [Error1 {errLoc = SS {sp_start = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1}, sp_stop = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1}}, errMsg = SortChecl: lookup in Empty Env }]' (after 32 tests):
        FlatAnfEnv {unFlatAnfEnv = Env {unEnv = fromList [("lq_anf$necmvtlyy",{mqgfcf : int | [(mqgfcf ~~
                            (&& [(vvhvaqbcfbr => ybzyzkjxclz);
                                 ("gltgdkgwdes" => "aouxfb");
                                 tabs vylzqqncup xpeqdfk] mod
                               || [exists [lrafyapmrw : @(-4);
                                           utznfu : Sdqrkejej;
                                           frgqwwyhggzp : func(0 , [func(1 , [@(3)]); Gdauhxtm])]
                                          . "xzecjwsu";
                                   forall [feaqzm : @(5);
                                           dszfdv : func(0 , [@(-5); rprjq; Porzvdevj])]
                                          . otygzfmkmv;
                                   tabs 3.0845977044261113 wrbzyynr]))]}),("lq_anf$gzgbktjtf",{vtnqjgfz : int | [(vtnqjgfz ~~
                              (((- ("rncexieck"))  :  func(1 , [func(0 , [frac; real]);
                                                                (frac int)])) (((lit "syanapeongfl" qgofelsxal) => "rriaxhalhsxn")  :  func(1 , [tdqzn]))))]}),("lq_anf$oqbgfllr",{evwnkc : int | [(evwnkc =
                            ((forall [rgzvzcbc : func(0 , [func(0 , [@(-5); gmknbh]);
                                                           (real num (frac num))]);
                                      rgxlexqztoo : Uppvmvipjfpo]
                                     . 1 => && [fsaeyreu; "upivdwrg"; "hmoyq"]) *
                               (- ((- (blmfxy))))))]}),("yuzjdkiklnbh",{zxcpas : int | [(zxcpas =
                            || [lq_anf$gzgbktjtf;
                                lq_anf$necmvtlyy;
                                lq_anf$oqbgfllr;
                                lq_anf$fzrutpnj;
                                lq_anf$hgdmbhzhzin;
                                lq_anf$vkjmidjrr])]}),("lq_anf$hgdmbhzhzin",{ysifnu : int | [(ysifnu ~~
                            ((qhbrtxkht 1.420470326002913e-2) && $ysuctabbsxxm -
                               ($lqwnegd[arbbk:=forall [jacfmom : func(1 , [Fkfavlwwn]);
                                                        qhyzwfeeggeo : gwwceprprd]
                                                       . exists [ojtnchtdp : Jynexgmkmr; xkgnc : Iiuncugn]
                                                                . ("lzwkhi"  :  @(-7))][lgogqljlv:=((- ($izipxn[osowgrrhjcp:=(- (|| [(coerce @(-6) ~ (func(0 , [func(0 , [int;
                                                                                                                                                                          int]);
                                                                                                                                                                (int frac)]) Qqoahw) in 2);
                                                                                                                                     && [3.8063749354727268;
                                                                                                                                         lrmfd;
                                                                                                                                         "nobtm"];
                                                                                                                                     ("cdpvqmuz" <=> "ukhqevzbduxv")]))])) exists [uwbezemb : Tqrwsgmr;
                                                                                                                                                                                   hxazh : @(-3);
                                                                                                                                                                                   ifzpg : func(0 , [func(0 , [(int frac);
                                                                                                                                                                                                               int;
                                                                                                                                                                                                               num]);
                                                                                                                                                                                                     func(1 , [frac]);
                                                                                                                                                                                                     xplphuxvk])]
                                                                                                                                                                                  . forall [dxukiciblmyv : Ztpqokxf;
                                                                                                                                                                                            vkzslawtl : func(0 , [func(0 , [func(0 , [num;
                                                                                                                                                                                                                                      int]);
                                                                                                                                                                                                                            @(0)]);
                                                                                                                                                                                                                  @(5)])]
                                                                                                                                                                                           . 5.2687182158699954)] => forall [xupmrpp : poghpzbzp;
                                                                                                                                                                                                                             bdqej : blkksoyf]
                                                                                                                                                                                                                            . ihmmsdgks)))]}),("lq_anf$fzrutpnj",{latikja : int | [(latikja ~~
                             (exists [hbugvaghudd : func(1 , [Fhpdogupsas]);
                                      gayisrf : func(1 , [(func(0 , [real; real]) func(1 , [int]))]);
                                      vvqcsvgla : func(0 , [func(1 , [num; num]); Dikqfmgtdga])]
                                     . tapp "lrqtxxgtc" (func(1 , [real;
                                                                   real]) fhqdver)  :  (rpzpxudsib func(0 , [Bxeqgryoxclw;
                                                                                                             Pztmyjmaevqv]))))]}),("lq_anf$vkjmidjrr",{dbggmgvpp : int | [(dbggmgvpp ~~
                               ((coerce @(-1) ~ Ifcmdydkn in || [(lit "uvttbjrcrtr" (Lupgai @(7)));
                                                                 4.874262773851095;
                                                                 "dytulgh"]) forall [dotiimeww : func(1 , [nypszlsisdnq]);
                                                                                     hknlonktqrlm : func(1 , [(@(-6) func(1 , [int]))])]
                                                                                    . (6.988209817035761 mod
                                                                                         "wzwgxojibq")))]})]}}
        Exception thrown while showing test case: 'Error [Error1 {errLoc = SS {sp_start = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1}, sp_stop = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1}}, errMsg = SortChecl: lookup in Empty Env }]'
        Use --quickcheck-replay=407282 --quickcheck-max-size=8 to reproduce.

1 out of 1 tests failed (0.02s)
*** Exception: ExitFailure 1
```

### PR DESCRIPTION
**Pull request by Fizzixnerd**
Fixes #557.

Three main changes: 

1. The error message in `SortCheck.hs` now prints the variable name on whom lookup failed.
2. Added shrinkers for the `Arbitrary` instances in `Arbitrary.hs`
3. Fixed the bug in the above issue: there were two problems, one was FVars outside of the scope of an FAbs, and the other was the generation of any FObj in a unification position would fail unification.  We now carefully only generate FVars when they are enclosed by a matching FAbs, and FObjs are not generated at all.

### CODE REVIEW

File: src/Language/Fixpoint/SortCheck.hs [hunk 1]
```diff
@@ -1131,7 +1131,7 @@ unifySorts :: Sort -> Sort -> Maybe TVSubst
 --------------------------------------------------------------------------------
 unifySorts   = unifyFast False emptyEnv
   where
-    emptyEnv = const $ die $ err dummySpan "SortChecl: lookup in Empty Env "
+    emptyEnv x = die $ err dummySpan $ "SortChecl: lookup in Empty Env: " <> pprint x
```
Comment (philderbeast) [inline src/Language/Fixpoint/SortCheck.hs]: This module is SortCheck. Is SortChecl a typo?

Comment (nikivazou) [reply src/Language/Fixpoint/SortCheck.hs]: yes!

Comment (Fizzixnerd) [reply src/Language/Fixpoint/SortCheck.hs]: Fixed.

File: tests/tasty/Arbitrary.hs [hunk 2]
```diff
@@ -143,34 +143,69 @@ instance Arbitrary KVar where
 instance Arbitrary GradInfo where
   arbitrary = pure $ GradInfo (SS pos pos) Nothing
     where pos = Spans.dummyPos "<unknown>"
+  shrink _ = mempty
```
Comment (facundominguez) [inline tests/tasty/Arbitrary.hs:149]: The documentation of `shrink` says the default method is `const []`. What difference does this change make?

File: tests/tasty/Arbitrary.hs [hunk 3]
```diff
@@ -143,34 +143,69 @@ instance Arbitrary KVar where
...
-  [ (1, FObj <$> arbitrary)
-  , (1, FVar <$> arbitrary)
-  , (1, FFunc <$> arbitrarySort' <*> arbitrarySort')
-  , (1, FAbs <$> arbitrary <*> arbitrarySort')
+arbitrarySort = arbitrarySortPossiblyInvolving Nothing
+
+-- | Create an arbitrary sort, possibly involving the first argument if Just.
+-- Can possibly create a `FAbs` that will also possibly reference the new
+-- variable in an `FVar`, even when the first argument is Nothing.
+arbitrarySortPossiblyInvolving :: Maybe Sort -> Int -> Gen Sort
```
Comment (facundominguez) [inline tests/tasty/Arbitrary.hs]: I'm not sure I understand these functions yet. It looks like `Maybe Sort` stands for a variable that is in scope. If that is the case, why not go instead with a type signature like:
```Haskell
arbitrarySortPossiblyInvolving :: [Int] -> Int -> Gen Sort
```
where `[Int]` stands for the list of identifiers of variables in scope?

File: tests/tasty/Arbitrary.hs (hunk 2 above)
Comment (Fizzixnerd) [reply tests/tasty/Arbitrary.hs:149]: The explicit implementation served as documentation when I was writing the shrinkers of which types I had written shrinkers for and in particular which types did not need a shrinker for whatever reason (since they had an explicit implementation of shrink).  However, I can remove it if you'd like.

File: tests/tasty/Arbitrary.hs (hunk 3 above)
Comment (Fizzixnerd) [reply tests/tasty/Arbitrary.hs]: You're right; I had originally done this to avoid shadowing, but I should still have to deal with it anyways, so I will change it.

File: tests/tasty/Arbitrary.hs (hunk 2 above)
Comment (Fizzixnerd) [reply tests/tasty/Arbitrary.hs:149]: Added comment.

File: tests/tasty/Arbitrary.hs (hunk 3 above)
Comment (Fizzixnerd) [reply tests/tasty/Arbitrary.hs]: Changed.

**Comment by facundominguez** [comment]
Thanks @Fizzixnerd. There are some compile errors in CI.

File: tests/tasty/Arbitrary.hs [hunk 4]
```diff
@@ -42,6 +42,10 @@ prop_pprint_parse_inv_expr expr = expr == rr (showpp expr)
 
 -}
 
+-- NOTE: Arbitrary instances in this file with an _explicit_ implementation of
+-- `shrink _ = mempty` are known to not have useful shrinker. Instances without
+-- an _explicit_ implementation have simply not been given a shrinker yet.
```
Comment (facundominguez) [inline tests/tasty/Arbitrary.hs]:
```suggestion
-- NOTE: `shrink _ = mempty` is identical to the default (implicit) shrink implementation.
-- We prefer to make it explicit.
```
